### ISSUE TITLE
Predicting bbox

### ISSUE THREAD

**Issue by danglive** [Epiphqny/Yolact_fcos#1]

**Comment by YuqingWang1029** [comment]
@danglive Can't understand your question, predicting the box is only used for nms, it can be replaced by mask nms later.

**Comment by danglive** [comment]
I'd like obtain the mAP the bbox. Could you show me how do that?

Thanks.

**Comment by YuqingWang1029** [comment]
The default inference code supports that. It predicts the mAP of bbox and
segm.

Tuan Dang <notifications@github.com>于2020年4月29日 周三下午5:39写道：
