### ISSUE TITLE
Inference speed 

### ISSUE THREAD

**Issue by abhigoku10** [Epiphqny/Yolact_fcos#3]
@Epiphqny  thanks for opensourcing your work just had few queries 

1. This repo is for yolact/ yolact++ 
2. what is the inference time obtained from your end

**Comment by YuqingWang1029** [comment]
@abhigoku10   You have asked the question in https://github.com/dbolya/yolact/issues/397 :)

**Comment by jiangxibao** [comment]
想问一下  训练YOLACT单个gpu需要训练多久

**Comment by YuqingWang1029** [comment]
@jiangxibao It takes about 3 days on 8 gpus, but you could try less number of convs in middle layers for fast speed. https://github.com/Epiphqny/Yolact_fcos/issues/2
